#!/bin/bash

if [ "$ACTION" = "remove" ]; then
        rm -f /dev/opi18b20
elif [ "$ACTION" = "add" ]; then
         major=$( sed -n 's/ opi18b20//p' /proc/devices )
       [ "$major" ] && mknod -m 0666 /dev/opi18b20 c $major 0
fi

exit 0
